apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secrets
type: Opaque
stringData:
  root: root_passwor
  xtrabackup: backup_password
  monitor: monitory
  clustercheck: clustercheckpasswor
  proxyadmin: admin_passwor
  pmmserver: admin
  operator: operatoradmi
